version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    user: 1000:1000
    ports:
      - "2828:2828"

  backend:
    container_name: backend
    image: backend
    env_file:
      - docker-backend.env
    build:
      context: .
    user: 1000:1000
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./lab4_2.0
    depends_on:
      - backend
    ports:
      - "3000:3000"